### ISSUE TITLE
Crash on 0.15.0

### ISSUE THREAD

**Issue by jslok** [RonRadtke/react-native-blob-util#133]
Just updated from 0.14.1 to 0.15.0 and it crashed on startup. RN 65.1 and 67.4.

![275427837_657025312228365_1356521695893427697_n](https://user-images.githubusercontent.com/22921326/160230530-d80c3da7-64aa-431c-a03d-60991e4fa6da.jpg)

**Comment by jslok** [comment]
react-native-blob-util is a dependency of redux-persist-filesystem-storage so I wonder if it is an issue with that.

**Comment by RonRadtke** [comment]
readFile only expects 4 arguments.
Sure there was a change to the method increasing the parameters from 3 to 4. But expecting 5 seems odd.
Could you please take a quick look at that line in your lib: https://github.com/RonRadtke/react-native-blob-util/blob/d52ba2ba5155252fd8a8e797dffd7684c59fcd17/android/src/main/java/com/ReactNativeBlobUtil/ReactNativeBlobUtil.java#L236
And check the amount of parameters expected for you. It looks everywhere fine in the code for me
@pcardon do you have the readFile in production with the transformer version and can check if that is an issue?

**Comment by cristianoccazinsp** [comment]
@RonRadtke keep in mind "this" is usually considered a parameter too (although passed implicitly).  I haven't updated yet so I cannot comment on this, but I wanted to make sure the latest updates are backwards compatible.

**Comment by RonRadtke** [comment]
> @RonRadtke keep in mind "this" is usually considered a parameter too (although passed implicitly). I haven't updated yet so I cannot comment on this, but I wanted to make sure the latest updates are backwards compatible.

I know but nothing changed except of an parameter being added, and that got added everywhere. And so far I was not able to reproduce the problem with my test environment.

The update is backwards compatible. (Besides that issue here which I can reproduce so far)

**Comment by pcardon** [comment]
The parameter was added on the native side, and the JS code is including the new parameter.  Is there a chance that you have some code that is calling the native side directly?  If so you would need to add the parameter.

**Comment by RonRadtke** [comment]
@pcardon just to make sure, did you try to clean the build cache and maybe even reinstall the lib?
Not that something got stuck there...

I'll keep digging tomorrow but no, i think every usage should be fixed. Especially every coming in globally and not using the fs module itself

**Comment by RonRadtke** [comment]
I actually managed to reproduce the issue now
1) Install react-native-blob-util 0.13.x
2) build app
3) update to 0.14.x or 0.15.x
4) build again
=> broken
5) `` npm start -- --reset-cache 
react-native start --reset-cache 
''
6) works as it should

so please try to reset the caches and try again

**Comment by RonRadtke** [comment]
It's ``npm start --reset-cache`` you have some "-" too much in your command

**Comment by jslok** [comment]
Ah I saw other guides say to include the extra --.

After `npm start --reset-cache` I still get the same error with rn blob util.

**Comment by dullkingsman** [comment]
@jslok have you found a fix for this? I have the same problem and I am stuck.

**Comment by jslok** [comment]
> @jslok have you found a fix for this? I have the same problem and I am stuck.

Nope. Just use 0.14.1

**Comment by jslok** [comment]
Error still showing on 0.16.0

**Comment by RonRadtke** [comment]
Could you share your code so I can try to build a test app out of it for reproducing the issue?
OF course feel free to build a small dumym yourself if you're able to :)

This issue kinda bugs me since I can't see any reason for so far, so I really would like to get it fixed....

**Comment by jslok** [comment]
Haven't had much time yet but I discovered this issue only happens when I use redux-persist-filesystem-storage. It does not happen when I swap that out with asyncstorage.

**Comment by RonRadtke** [comment]
Are you using the library besides of redux-persist-filesystem-storage?

**Comment by jslok** [comment]
> Are you using the library besides of redux-persist-filesystem-storage?

Yes

**Comment by RonRadtke** [comment]
Could you try to use this pull request for once?
https://github.com/robwalkerco/redux-persist-filesystem-storage/pull/60
I'm wondering if it's just an issue with the version missmatch

**Comment by ryansommers** [comment]
@RonRadtke I was getting this same error and use redux-persist-filesystem-storage as well. The pull request you linked fixed the error.

**Comment by RonRadtke** [comment]
Thank!
I created an issue for: https://github.com/robwalkerco/redux-persist-filesystem-storage/issues/61

But then we can't really do much here to get it fixed

**Comment by RonRadtke** [comment]
redux-persistent-file-system merged the PR. After upgrading your lib version it should work
